const VERSION='zaenid-michis-v21';
const STATIC=['./','./index.html','./manifest.json','./launcher.html','./icon-192.png','./icon-512.png'];
const EXTERNAL=[
  'https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js',
  'https://www.gstatic.com/firebasejs/10.12.0/firebase-database-compat.js',
  'https://www.gstatic.com/firebasejs/10.12.0/firebase-auth-compat.js'
];
const REPLACEMENTS=[
  ["async function durableWrite(op,path,value){localApply(path,op==='remove'?undefined:value,op==='patch');if(!navigator.onLine){queue(op,path,value);return}try{await Promise.race([netWrite(op,path,value),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),5000))])}catch{queue(op,path,value)}}",
   "function durableWrite(op,path,value){localApply(path,op==='remove'?undefined:value,op==='patch');if(!navigator.onLine){queue(op,path,value);return Promise.resolve()}Promise.race([netWrite(op,path,value),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),5000))]).catch(()=>queue(op,path,value));return Promise.resolve()}"],
  ["online:navigator.onLine,unsubs:[],viewUnsubs:[]};",
   "online:navigator.onLine,deletingTasks:{},unsubs:[],viewUnsubs:[]};"],
  ["function localDate(d=new Date()){",
   "function updatePendingCareBanner(){document.getElementById('pendingCareAlert')?.remove();if(state.tab!=='care'||state.date!==localDate())return;const pending=CATS.filter(c=>{const r=state.daily[c.id]||{};return !((r.am||r.pm)&&r.ate&&r.water&&r.litter)});if(!pending.length)return;const toolbar=document.querySelector('.toolbar');if(!toolbar)return;const box=document.createElement('button');box.id='pendingCareAlert';box.type='button';box.style.cssText='width:100%;border:1px solid #f59e0b;background:#fffbeb;color:#92400e;border-radius:12px;padding:10px 12px;margin-top:9px;font-weight:800;text-align:left';box.textContent=`⚠️ ${pending.length} ${pending.length===1?'cat still needs':'cats still need'} care today — View pending`;box.onclick=()=>{state.filter='pending';render()};toolbar.appendChild(box)}function localDate(d=new Date()){"
  ],
  ["if(state.filter==='pending'&&r.am&&r.pm)return false;return true",
   "if(state.filter==='pending'&&(r.am||r.pm)&&r.ate&&r.water&&r.litter)return false;if(state.filter==='meds'&&!(r.medRequired||r.med||r.medNotes))return false;return true"],
  ["[['all','All 128'],['urgent','⚠️ Urgent'],['pending','○ Pending']]",
   "[['all','All 128'],['urgent','⚠️ Urgent'],['pending','○ Pending Care'],['meds','💊 Meds']]"],
  ["<button class=\"urgentbtn ${r.urgent?'on':''}\" data-care=\"urgent\">${r.urgent?'⚠️ URGENT — Tap to clear':'Mark as URGENT ⚠️'}</button><div class=\"checks\">${[['am','☀️','AM'],['pm','🌙','PM'],['ate','🍽️','Food'],['water','💧','Water'],['litter','🪣','Litter'],['med','💊','Med']]",
   "<button class=\"urgentbtn ${r.urgent?'on':''}\" data-care=\"urgent\">${r.urgent?'⚠️ URGENT — Tap to clear':'Mark as URGENT ⚠️'}</button><button class=\"urgentbtn ${r.medRequired?'on':''}\" style=\"margin-top:8px;${r.medRequired?'background:#7c3aed;border-color:#7c3aed':''}\" data-care=\"medRequired\">${r.medRequired?'💊 MEDICATION REQUIRED — Tap to clear':'💊 Mark medication required'}</button><div class=\"checks\">${[['am','☀️','AM'],['pm','🌙','PM'],['ate','🍽️','Food'],['water','💧','Water'],['litter','🪣','Litter'],['med','💊','Med Given']]"],
  ["<button class=\"btn small\" data-task-del=\"${esc(t._key)}\">Delete</button>",
   "<button class=\"task-x\" type=\"button\" aria-label=\"Delete task\" title=\"Delete task\" data-task-del=\"${esc(t._key)}\">×</button>"],
  ["const tasks=state.tasks.filter(t=>t.date===today&&(coord||t.personId===state.person.uid));",
   "const tasks=state.tasks.filter(t=>!state.deletingTasks[t._key]&&t.date===today&&(coord||t.personId===state.person.uid));"],
  ["state.unsubs.push(db.listen('sag_tasks',v=>{state.tasks=normalizeTasks(v);render()}))",
   "state.unsubs.push(db.listen('sag_tasks',v=>{state.tasks=normalizeTasks(v).filter(t=>!state.deletingTasks[t._key]);render()}))"],
  ["async function deleteTask(key){if(confirm('Delete this task?'))await db.remove(`sag_tasks/${key}`)}",
   "function deleteTask(key){if(!key||state.deletingTasks[key])return;state.deletingTasks[key]=true;state.tasks=state.tasks.filter(t=>t._key!==key);render();db.remove(`sag_tasks/${key}`)}"],
  ["if(t.dataset.taskDel){deleteTask(t.dataset.taskDel);return}",
   "if(t.dataset.taskDel){const card=t.closest('.task');if(card)card.remove();deleteTask(t.dataset.taskDel);return}"],
  [".task-actions{display:flex;gap:7px;margin-top:10px}",
   ".task-actions{display:flex;gap:7px;margin-top:10px}.task-x{margin-left:auto;width:56px;height:56px;min-width:56px;border:0;border-radius:16px;background:#fee2e2;color:#b91c1c;font-size:34px;line-height:1;font-weight:700;display:grid;place-items:center;touch-action:none;-webkit-user-select:none;user-select:none}.task-x:active{transform:scale(.94);background:#fecaca}"],
  [".login .card{padding:22px;box-shadow:0 24px 70px #0006}",
   ".login .card{padding:22px;box-shadow:0 24px 70px #0006}.login input{min-height:48px}"],
  ["<body><h2>Zaenid Michis — Care Report</h2>",
   "<body><button id=\"reportBack\" onclick=\"if(window.opener&&!window.opener.closed){window.opener.focus();window.close();return}else{location.href='./'}\" style=\"display:inline-block;border:0;border-radius:10px;background:#0f172a;color:white;padding:10px 14px;font-weight:700;margin-bottom:14px\">← Back to Zaenid Michis</button><h2>Zaenid Michis — Care Report</h2>"],
  ["<script>window.onload=()=>window.print()<\\/script>",
   "<script>window.onload=()=>window.print();window.onafterprint=()=>setTimeout(()=>{if(window.opener&&!window.opener.closed){window.opener.focus();window.close()}},250)<\\/script>"],
  ["function openPhotoModal(){const cat=CATS.find(c=>c.id===state.photoCat);if(!cat)return;const ph=state.catPhotos[cat.id]||'';const modal=document.createElement('div');modal.className='modalbg';modal.id='photoModal';modal.innerHTML=`<div class=\"modal\"><div class=\"modalhead\"><h3>Photo — ${esc(cat.name)}</h3><button class=\"close\" data-act=\"closePhoto\">×</button></div><div class=\"field\"><label>Direct Photo URL</label><input id=\"photoUrl\" class=\"input\" value=\"${esc(ph)}\" placeholder=\"https://…\"></div><div class=\"muted mb12\">Use a direct image URL. Some Google Photos/Drive share links do not work as image links.</div><button class=\"btn primary w100\" data-act=\"savePhoto\">Save Photo</button></div>`;document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal){state.photoCat=null;modal.remove()}else handleClick(e)})}",
   "function openPhotoModal(){const cat=CATS.find(c=>c.id===state.photoCat);if(!cat)return;const ph=state.catPhotos[cat.id]||'';const modal=document.createElement('div');modal.className='modalbg';modal.id='photoModal';modal.innerHTML=`<div class=\"modal\"><div class=\"modalhead\"><h3>Photo — ${esc(cat.name)}</h3><button class=\"close\" data-act=\"closePhoto\">×</button></div>${ph?`<div style=\"text-align:center;margin-bottom:14px\"><img src=\"${esc(ph)}\" alt=\"${esc(cat.name)}\" style=\"width:140px;height:140px;object-fit:cover;border-radius:18px;border:1px solid var(--line)\"></div>`:''}<div class=\"field\"><label>Select Photo</label><input id=\"photoFile\" class=\"input\" type=\"file\" accept=\"image/*\"></div><div class=\"muted mb12\">Choose a photo from the phone gallery/camera or from the computer. The app reduces it automatically before saving.</div><div id=\"photoMsg\"></div><button class=\"btn primary w100\" data-act=\"savePhoto\">${ph?'Replace Photo':'Save Photo'}</button></div>`;document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal){state.photoCat=null;modal.remove()}else handleClick(e)})}"],
  ["async function savePhoto(){const url=document.getElementById('photoUrl').value.trim(),id=state.photoCat;if(url)await db.set(`sag_cat_photos/${id}`,url);else await db.remove(`sag_cat_photos/${id}`);state.photoCat=null;document.getElementById('photoModal')?.remove();render()}",
   "function compressPhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('read'));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('decode'));img.onload=()=>{try{const max=360,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale));const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',0.68))}catch(e){reject(e)}};img.src=reader.result};reader.readAsDataURL(file)})}async function savePhoto(){const file=document.getElementById('photoFile')?.files?.[0],id=state.photoCat,msg=document.getElementById('photoMsg');if(!file){if(msg)msg.innerHTML='<div class=\"msg err\">Select a photo first.</div>';return}if(!file.type.startsWith('image/')){if(msg)msg.innerHTML='<div class=\"msg err\">Please choose an image file.</div>';return}if(!navigator.onLine){if(msg)msg.innerHTML='<div class=\"msg err\">Internet is required to save a photo.</div>';return}const btn=document.querySelector('[data-act=\"savePhoto\"]');if(btn){btn.disabled=true;btn.textContent='Saving…'}try{const photo=await compressPhoto(file);if(photo.length>350000)throw new Error('too-large');await db.set(`sag_cat_photos/${id}`,photo);state.photoCat=null;document.getElementById('photoModal')?.remove();render()}catch(e){console.error(e);if(msg)msg.innerHTML='<div class=\"msg err\">Could not save this photo. Try another image.</div>';if(btn){btn.disabled=false;btn.textContent=state.catPhotos[id]?'Replace Photo':'Save Photo'}}}function removePhoto(id){if(confirm('Remove photo?'))db.remove(`sag_cat_photos/${id}`)}"],
  ["if(t.dataset.photoRemove){if(confirm('Remove photo?'))db.remove(`sag_cat_photos/${t.dataset.photoRemove}`);return}",
   "if(t.dataset.photoRemove){removePhoto(t.dataset.photoRemove);return}"],
  ["function render(){if(state.authState==='loading')",
   "function render(){document.querySelectorAll('.modalbg').forEach(el=>el.remove());setTimeout(updatePendingCareBanner,0);if(state.authState==='loading')"],
  ["function openCatModal(){const cat=",
   "function openCatModal(){document.querySelectorAll('.modalbg').forEach(el=>el.remove());const cat="],
  ["function openPhotoModal(){const cat=",
   "function openPhotoModal(){document.querySelectorAll('.modalbg').forEach(el=>el.remove());const cat="],
  ["function openPersonModal(){const isNew=",
   "function openPersonModal(){document.querySelectorAll('.modalbg').forEach(el=>el.remove());const isNew="],
  ["document.getElementById('catModal')?.remove()",
   "document.querySelectorAll('.modalbg').forEach(el=>el.remove())"],
  ["document.getElementById('photoModal')?.remove()",
   "document.querySelectorAll('.modalbg').forEach(el=>el.remove())"],
  ["document.getElementById('personModal')?.remove()",
   "document.querySelectorAll('.modalbg').forEach(el=>el.remove())"],
  ["function bindClicks(){app.onclick=handleClick;const cs=document.getElementById('catSearch');cs?.addEventListener('input',e=>{state.search=e.target.value;render()});const hd=document.getElementById('histDate');hd?.addEventListener('change',e=>{state.date=e.target.value;bindDaily();render()})}",
   "function bindClicks(){app.onclick=handleClick;app.querySelectorAll('[data-task-del]').forEach(btn=>{btn.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const key=btn.dataset.taskDel;if(!key||btn.dataset.busy==='1')return;btn.dataset.busy='1';btn.disabled=true;deleteTask(key)};btn.onclick=e=>{e.preventDefault();e.stopPropagation()}});const cs=document.getElementById('catSearch');cs?.addEventListener('input',e=>{state.search=e.target.value;render()});const hd=document.getElementById('histDate');hd?.addEventListener('change',e=>{state.date=e.target.value;bindDaily();render()})}"
  ]
];
function patchedHtml(text){for(const [from,to] of REPLACEMENTS)if(text.includes(from))text=text.replace(from,to);return text}
async function cachePatchedIndex(cache){try{const r=await fetch('./index.html',{cache:'reload'});const text=patchedHtml(await r.text());const response=new Response(text,{status:200,headers:{'Content-Type':'text/html; charset=utf-8'}});await cache.put('./index.html',response.clone());await cache.put('./',response)}catch{}}
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(VERSION);await Promise.allSettled(STATIC.filter(x=>x!=='./'&&x!=='./index.html').map(x=>cache.add(x)));await cachePatchedIndex(cache);await Promise.allSettled(EXTERNAL.map(async url=>{try{const response=await fetch(url,{mode:'no-cors',cache:'reload'});await cache.put(url,response)}catch{}}));await self.skipWaiting()})())});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==VERSION).map(k=>caches.delete(k)));await self.clients.claim()})())});
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin===location.origin){event.respondWith((async()=>{const cache=await caches.open(VERSION);const isHtml=req.mode==='navigate'||url.pathname.endsWith('/')||url.pathname.endsWith('/index.html');try{const fresh=await fetch(req,{cache:'no-store'});if(isHtml){const text=patchedHtml(await fresh.text());const out=new Response(text,{status:fresh.status,statusText:fresh.statusText,headers:fresh.headers});await cache.put(req,out.clone());return out}if(fresh&&fresh.ok)await cache.put(req,fresh.clone());return fresh}catch{const cached=(await cache.match(req))||(isHtml?await cache.match('./index.html'):null);if(!cached)return Response.error();if(!isHtml)return cached;const text=patchedHtml(await cached.text());return new Response(text,{status:200,headers:{'Content-Type':'text/html; charset=utf-8'}})}})());return}if(url.hostname==='www.gstatic.com'){event.respondWith((async()=>{const cached=await caches.match(req);if(cached)return cached;try{const fresh=await fetch(req);const cache=await caches.open(VERSION);await cache.put(req,fresh.clone());return fresh}catch{return Response.error()}})())}});